version: '2'
services:
    brewcoffe-app:
        image: brewcoffe
            - brewcoffe-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/brewcoffe
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    brewcoffe-mariadb:
        extends:
            file: mariadb.yml
            service: brewcoffe-mariadb
